apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
        - name: conversao-peso
          image: speckbr/conversao-peso:v1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-peso
spec:
  selector:
    app: conversao-peso
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort
